name: Generate Changelog and Update Version

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      new_version: ${{ steps.semver.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # this prevents GitHub actions from overriding

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  # use a stable LTS version

      - name: Clear Node Modules
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm install

      - name: Generate Changelog and Bump Version
        id: semver
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # Make sure PAT is configured in your repo settings