name: Update Version in setup.py on Release

on:
  release:
    types: [created]

jobs:
  update-version-in-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Extract the version number from the release tag
        id: get_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update version in setup.py
        run: |
          echo "New version is ${{ needs.generate-changelog.outputs.new_version }}"
          python .github/scripts/update_version.py "${{ needs.generate-changelog.outputs.new_version }}"
        working-directory: ./

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git diff
          git add setup.py
          git commit -m "chore: bump version to $RELEASE_VERSION" || exit 0 # This will not fail if no changes
          git push
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
